### ISSUE TITLE
Organize Scan Summary Page 

### ISSUE THREAD

**Issue by zimventures** [mantiumai/chirps#42]
Each individual scan has a summary page found at `/scan/result/<id>`. The summary page lists all of the findings for the scan. More information will be gradually added to this page, and as such, it needs to have organizational components added. 

# Tabs
In order to better organize aspects of a scan, tab-navigation will be added to the top of the page. Each tab will display a specific set of data. The following sections will detail each of the tabs, and what should be rendered in them.

## Scan Summary
The summary is meant to show a high level overview of what happened during the scan. Components shown to the user should include:

- [ ] Scan duration
- [ ] Scan start/stop time
- [ ] Pie chart showing the breakdown of findings, based on severity
- [ ] Link to the Plans used for the scan
- [ ] Link to the Target used for the scan

## Scan Findings (details)
This tab will show a detailed list of all the findings for a scan. The list will be what is currently found in the summary page (rule name, severity, findings) plus details of all the findings. 

## Scan History
This is a placeholder tab that shows details of actions taken by the user after the scan. The intention is that eventually a user will perform mitigation actions such as marking a finding as a false positive, re-run the scan, or mark a finding as fixed. 

#### TODO: URL Update
The URL for viewing the details of a scan should be updated to simply be `/scan/<id>`. In short, remove the `result` path from the URL.
